<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    public function run()
    {
        DB::table('properties')->insert([
            [
                'agent_id' => 1,
                'judul' => 'Modern House in Jakarta',
                'harga' => 2500000000,
                'daerah' => 'Kebayoran Baru',
                'wilayah' => 'Jakarta Selatan',
                'provinsi' => 'DKI Jakarta',
                'satuan_luas' => 'm2',
                'lt' => 300,
                'lb' => 400,
                'kt' => 4,
                'km' => 3,
                'kt_p' => 1,
                'km_p' => 1,
                'hadap' => 'Timur',
                'lantai' => 2,
                'listrik' => 4400,
                'status_p' => 'Dijual',
                'jenis_p' => 'Rumah',
                'tipe_p' => 'Modern',
                'deskripsi' => 'Rumah modern dengan desain minimalis, cocok untuk keluarga.',
                'image' => 'house1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 2,
                'judul' => 'Apartment in PIK 2',
                'harga' => 1500000000,
                'daerah' => 'Pantai Indah Kapuk',
                'wilayah' => 'Jakarta Utara',
                'provinsi' => 'DKI Jakarta',
                'satuan_luas' => 'm2',
                'lt' => 80,
                'lb' => 90,
                'kt' => 2,
                'km' => 2,
                'kt_p' => 0,
                'km_p' => 0,
                'hadap' => 'Barat',
                'lantai' => 10,
                'listrik' => 2200,
                'status_p' => 'Disewakan',
                'jenis_p' => 'Apartemen',
                'tipe_p' => 'Luxury',
                'deskripsi' => 'Apartemen dengan fasilitas premium di area strategis PIK 2.',
                'image' => 'apartment1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 3,
                'judul' => 'Cozy Villa in Bali',
                'harga' => 5000000000,
                'daerah' => 'Ubud',
                'wilayah' => 'Gianyar',
                'provinsi' => 'Bali',
                'satuan_luas' => 'm2',
                'lt' => 500,
                'lb' => 450,
                'kt' => 3,
                'km' => 2,
                'kt_p' => 1,
                'km_p' => 1,
                'hadap' => 'Selatan',
                'lantai' => 1,
                'listrik' => 3500,
                'status_p' => 'Dijual',
                'jenis_p' => 'Villa',
                'tipe_p' => 'Tradisional',
                'deskripsi' => 'Villa nyaman dengan pemandangan sawah yang indah, lokasi tenang di Ubud.',
                'image' => 'villa1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 1,
                'judul' => 'Luxury Penthouse in Surabaya',
                'harga' => 8000000000,
                'daerah' => 'Darmo',
                'wilayah' => 'Surabaya Barat',
                'provinsi' => 'Jawa Timur',
                'satuan_luas' => 'm2',
                'lt' => 350,
                'lb' => 350,
                'kt' => 3,
                'km' => 3,
                'kt_p' => 1,
                'km_p' => 1,
                'hadap' => 'Utara',
                'lantai' => 20,
                'listrik' => 6600,
                'status_p' => 'Dijual',
                'jenis_p' => 'Penthouse',
                'tipe_p' => 'Luxury',
                'deskripsi' => 'Penthouse mewah dengan pemandangan kota, dekat pusat perbelanjaan.',
                'image' => 'penthouse1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 4,
                'judul' => 'Commercial Building in Bandung',
                'harga' => 3000000000,
                'daerah' => 'Dago',
                'wilayah' => 'Bandung Utara',
                'provinsi' => 'Jawa Barat',
                'satuan_luas' => 'm2',
                'lt' => 600,
                'lb' => 700,
                'kt' => 0,
                'km' => 4,
                'kt_p' => 0,
                'km_p' => 0,
                'hadap' => 'Barat',
                'lantai' => 3,
                'listrik' => 11000,
                'status_p' => 'Disewakan',
                'jenis_p' => 'Komersial',
                'tipe_p' => 'Gedung',
                'deskripsi' => 'Gedung komersial di lokasi strategis, cocok untuk kantor atau bisnis.',
                'image' => 'building1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 5,
                'judul' => 'Townhouse in Bekasi',
                'harga' => 2000000000,
                'daerah' => 'Galaxy',
                'wilayah' => 'Bekasi Selatan',
                'provinsi' => 'Jawa Barat',
                'satuan_luas' => 'm2',
                'lt' => 200,
                'lb' => 180,
                'kt' => 3,
                'km' => 2,
                'kt_p' => 0,
                'km_p' => 0,
                'hadap' => 'Utara',
                'lantai' => 2,
                'listrik' => 3500,
                'status_p' => 'Dijual',
                'jenis_p' => 'Townhouse',
                'tipe_p' => 'Modern',
                'deskripsi' => 'Townhouse modern di lingkungan aman, dekat dengan sekolah dan mall.',
                'image' => 'townhouse1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'agent_id' => 6,
                'judul' => 'Warehouse in Tangerang',
                'harga' => 10000000000,
                'daerah' => 'Jatake',
                'wilayah' => 'Tangerang',
                'provinsi' => 'Banten',
                'satuan_luas' => 'm2',
                'lt' => 1200,
                'lb' => 1000,
                'kt' => 0,
                'km' => 2,
                'kt_p' => 0,
                'km_p' => 0,
                'hadap' => 'Timur',
                'lantai' => 1,
                'listrik' => 16000,
                'status_p' => 'Disewakan',
                'jenis_p' => 'Gudang',
                'tipe_p' => 'Industrial',
                'deskripsi' => 'Gudang luas dengan akses tol, cocok untuk bisnis logistik dan distribusi.',
                'image' => 'warehouse1.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        
    }
}
